version: '3'

services:
  uvncrepeater:
    build:
      context: .
      dockerfile: docker/uvncrepeater/Dockerfile
    volumes:
      - log_volume:/var/log/
      - etc_uvnc_volume:/etc/uvnc/
    stdin_open: true 
    tty: true        

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
      - log_volume:/uvnc/var/log/
      - etc_uvnc_volume:/uvnc/etc/uvnc/
    links:
      - php
    stdin_open: true 
    tty: true       

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/
      - log_volume:/uvnc/var/log/
      - etc_uvnc_volume:/uvnc/etc/uvnc/
    stdin_open: true 
    tty: true       

volumes:
  log_volume: 
  etc_uvnc_volume:
